### PR TITLE
Changed: The 'Installation' block of the README

### LINKED ISSUE #27: Build failure with latest go 1.12.6
I am trying to build the project following instructions using latest go `1.12.6` but i get the following error:

```
user@host:~# go get -u github.com/cycloidio/terracognita 
# github.com/cycloidio/terracognita/aws
programmi/go/src/github.com/cycloidio/terracognita/aws/provider.go:46:32: impossible type assertion:
	*"github.com/hashicorp/terraform/helper/schema".Provider does not implement "github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".ResourceProvider (wrong type for Apply method)
		have Apply(*"github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/hashicorp/terraform/terraform".InstanceState, error)
		want Apply(*"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".InstanceInfo, *"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".InstanceState, *"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".InstanceDiff) (*"github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/terraform".InstanceState, error)
```

### PR DESCRIPTION
**Pull request by xescugc**
Was outdated and not working correctly so I've updated it with more up to date information.

Also added the `make install` to make it easy to use.

Closes #27

### CODE REVIEW

**Comment by najeal** [comment]
Add `GO111MODULE=on go get github.com/cycloidio/terracognita`? Only the `-u` trying to update dependencies to minors versions is failing.

**Comment by xescugc** [comment]
If you use `go get` in a module env `GO111MODULE=on` it installs it as a pakage so inside the `pkg/mod` no on the `src/...` that's where you may want it to play with. The best solution is the `-d` or to just clone it.

**Comment by najeal** [comment]
I agree. But even if it installs it as package in the `pkg/mod`, it installs it also as bin in `bin` and I can directly start to play with the command line.

**Comment by xescugc** [comment]
If he wants to do that then do it manually, the supported way it's using the Makefile as it's the one that also adds the `version` to the build, doing a simple install will end up being versionless and we don't want that (will not be able to report bugs as no verison would be available).

I would even prefer to just add the option to Clone and not to `get` so we force the user of the tools we need too.

**Pull request merged**
